### PR TITLE
Update deps and CTS

### PR DESCRIPTION
**Pull request by kpet**
Here are a few regressions I'm observing with this update:

AMD/Intel/llvmpipe (logical and physical addressing)

```
        Half Ops
                Expected the return code to be 0 but got 1
                Expected the status of 'vloada_half' to be 'pass' but got 'fail'
                Expected the status of 'vstorea_half' to be 'pass' but got 'fail'
                Expected the status of 'vstorea_half_rte' to be 'pass' but got 'fail'
                Expected the status of 'vstorea_half_rtz' to be 'pass' but got 'fail'
                Expected the status of 'vstorea_half_rtp' to be 'pass' but got 'fail'
                Expected the status of 'vstorea_half_rtn' to be 'pass' but got 'fail'
```

Intel/llvmpipe (logical and physical addressing)
 
```             
        Images (clFillImage pitch)
                Expected the return code to be 0 but got -11
                Got reference for test '1D' but no result
                Got reference for test '1Darray' but no result
                Got reference for test '2D' but no result
                Got reference for test '2Darray' but no result
                Got reference for test '3D' but no result
```
             
Intel (physical addressing)

```
        Printf
                Expected the return code to be 0 but got 1
                Expected the status of 'address_space_0' to be 'pass' but got 'fail'
                Expected the status of 'address_space_1' to be 'pass' but got 'fail'
                Expected the status of 'address_space_4' to be 'pass' but got 'fail'
        Vectors
                Expected the return code to be 0 but got 1
                Expected the status of 'vec_align_struct' to be 'pass' but got 'fail'
```

Change-Id: Ie2b11d3f0b0297121a085e76d05da5f74af46aca

### CODE REVIEW

**Comment by kpet** [comment]
FYI @rjodinchr in case the above list of regressions is of interest.

**Comment by kpet** [comment]
@rjodinchr It looks like the libclc changes aren't passing the Android CI.

**Comment by rjodinchr** [comment]
> @rjodinchr It looks like the libclc changes aren't passing the Android CI.

Is there a way to know/update the cmake version used in this Android CI?

**Comment by kpet** [comment]
I couldn't find anything obvious in the logs. We should be able to update it and/or start using docker images. Do you know what version is needed?

**Comment by rjodinchr** [comment]
> I couldn't find anything obvious in the logs. We should be able to update it and/or start using docker images. Do you know what version is needed?

I don't know, but maybe the minimum required version in llvm is not well set, that's why the failure is hard to understand with just the logs.
I don't have lots of ideas looking at the failure, and I'm not sure how I could try to reproduce it to debug.

**Comment by rjodinchr** [comment]
The issue is with cross compiling.
I guess the workaround at the moment, would be to build manually libclc for android.... ☹
That's what I am going to do for ChromeOS.

**Comment by rjodinchr** [comment]
I have a PR in clspv to allow building with external libclc libraries: https://github.com/google/clspv/pull/1366

**Comment by rjodinchr** [comment]
I am not able to reproduce the clFillImage issues with llvmpipe.

**Comment by rjodinchr** [comment]
In fact I'm not able to reproduce anything. I have un clFillImage and Printf with and without physical addressing on llvmpipe and Intel, but everything seems to work well on my side.

**Comment by rjodinchr** [comment]
How do you want to handle android?

**Comment by rjodinchr** [comment]
https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/5581355

**Comment by kpet** [comment]
Superseded by @rjodinchr's PR.

**Pull request closed without merging**
