### PR TITLE
Update deps and CTS

### PR DESCRIPTION
**Pull request by kpet**
Change-Id: Ia6582371c286fd43e8afa41e50793165d24c9bfd

### CODE REVIEW

**Comment by kpet** [comment]
@rjodinchr I've resolved my hardware issues and most of the failures I reported with the last update were, as suspected, spurious. Here are the regressions that remain (all on AMD HW):
- async_strided_copy_local_to_global
- async_strided_copy_global_to_local
- Samplerless 3D (the validation layers are reporting issues; clvk is not configuring samplers correctly)

I've also dropped all the patches to the conversions suite I still had on my CTS branch and updated past the recent refactoring. Pretty much all subtests are passing except the following (Intel HW):

```
642) Testing convert_floatn_rtp( ulongn ):
Building convert_float_rtp( ulong ) test
Building convert_float2_rtp( ulong2 ) test
Building convert_float3_rtp( ulong3 ) test
Building convert_float4_rtp( ulong4 ) test
Building convert_float8_rtp( ulong8 ) test
Building convert_float16_rtp( ulong16 ) test
Testing... .
Error for vector size 2 found at 0x00000040:  *0x1p+64 vs 0x1.000002p+64

Error for vector size 3 found at 0x00000040:  *0x1p+64 vs 0x1.000002p+64

Error for vector size 4 found at 0x00000040:  *0x1p+64 vs 0x1.000002p+64
Input value: 0xfffffffffffffffe  (convert_float2_rtp( ulong2 ))
         *** 642) convert_floatn_rtp( ulongn ) FAILED ** 
643) Testing convert_floatn_rtn( ulongn ):
Building convert_float_rtn( ulong ) test
Building convert_float2_rtn( ulong2 ) test
Building convert_float3_rtn( ulong3 ) test
Building convert_float4_rtn( ulong4 ) test
Building convert_float8_rtn( ulong8 ) test
Building convert_float16_rtn( ulong16 ) test
Testing... .
Error for vector size 2 found at 0x00000040:  *0x1.fffffep+63 vs 0x1p+64

Error for vector size 3 found at 0x00000040:  *0x1.fffffep+63 vs 0x1p+64

Error for vector size 4 found at 0x00000040:  *0x1.fffffep+63 vs 0x1p+64
Input value: 0xfffffffffffffffe  (convert_float2_rtn( ulong2 ))
         *** 643) convert_floatn_rtn( ulongn ) FAILED ** 
644) Testing convert_floatn_rtz( ulongn ):
Building convert_float_rtz( ulong ) test
Building convert_float2_rtz( ulong2 ) test
Building convert_float3_rtz( ulong3 ) test
Building convert_float4_rtz( ulong4 ) test
Building convert_float8_rtz( ulong8 ) test
Building convert_float16_rtz( ulong16 ) test
Testing... .
Error for vector size 2 found at 0x00000040:  *0x1.fffffep+63 vs 0x1p+64

Error for vector size 3 found at 0x00000040:  *0x1.fffffep+63 vs 0x1p+64

Error for vector size 4 found at 0x00000040:  *0x1.fffffep+63 vs 0x1p+64
Input value: 0xfffffffffffffffe  (convert_float2_rtz( ulong2 ))
         *** 644) convert_floatn_rtz( ulongn ) FAILED ** 
647) Testing convert_floatn_rtp( longn ):
Building convert_float_rtp( long ) test
Building convert_float2_rtp( long2 ) test
Building convert_float3_rtp( long3 ) test
Building convert_float4_rtp( long4 ) test
Building convert_float8_rtp( long8 ) test
Building convert_float16_rtp( long16 ) test
Testing... .
Error for vector size 2 found at 0x0000007f:  *0x1p+63 vs 0x1.000002p+63

Error for vector size 3 found at 0x0000007f:  *0x1p+63 vs 0x1.000002p+63

Error for vector size 4 found at 0x0000007f:  *0x1p+63 vs 0x1.000002p+63
Input value: 0x7fffffffffffffff  (convert_float2_rtp( long2 ))
         *** 647) convert_floatn_rtp( longn ) FAILED ** 
765) Testing convert_ulongn_sat( floatn ):
Building convert_ulong_sat( float ) test
Building convert_ulong2_sat( float2 ) test
Building convert_ulong3_sat( float3 ) test
Building convert_ulong4_sat( float4 ) test
Building convert_ulong8_sat( float8 ) test
Building convert_ulong16_sat( float16 ) test
Testing... .
Error for vector size 2 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 3 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 4 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000
Input value: inf  (convert_ulong2_sat( float2 ))
         *** 765) convert_ulongn_sat( floatn ) FAILED ** 
766) Testing convert_ulongn_sat_rte( floatn ):
Building convert_ulong_sat_rte( float ) test
Building convert_ulong2_sat_rte( float2 ) test
Building convert_ulong3_sat_rte( float3 ) test
Building convert_ulong4_sat_rte( float4 ) test
Building convert_ulong8_sat_rte( float8 ) test
Building convert_ulong16_sat_rte( float16 ) test
Testing... .
Error for vector size 2 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 3 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 4 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000
Input value: inf  (convert_ulong2_sat_rte( float2 ))
         *** 766) convert_ulongn_sat_rte( floatn ) FAILED ** 
767) Testing convert_ulongn_sat_rtp( floatn ):
Building convert_ulong_sat_rtp( float ) test
Building convert_ulong2_sat_rtp( float2 ) test
Building convert_ulong3_sat_rtp( float3 ) test
Building convert_ulong4_sat_rtp( float4 ) test
Building convert_ulong8_sat_rtp( float8 ) test
Building convert_ulong16_sat_rtp( float16 ) test
Testing... .
Error for vector size 2 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 3 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 4 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000
Input value: inf  (convert_ulong2_sat_rtp( float2 ))
         *** 767) convert_ulongn_sat_rtp( floatn ) FAILED ** 
768) Testing convert_ulongn_sat_rtn( floatn ):
Building convert_ulong_sat_rtn( float ) test
Building convert_ulong2_sat_rtn( float2 ) test
Building convert_ulong3_sat_rtn( float3 ) test
Building convert_ulong4_sat_rtn( float4 ) test
Building convert_ulong8_sat_rtn( float8 ) test
Building convert_ulong16_sat_rtn( float16 ) test
Testing... .
Error for vector size 2 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 3 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 4 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000
Input value: inf  (convert_ulong2_sat_rtn( float2 ))
         *** 768) convert_ulongn_sat_rtn( floatn ) FAILED ** 
769) Testing convert_ulongn_sat_rtz( floatn ):
Building convert_ulong_sat_rtz( float ) test
Building convert_ulong2_sat_rtz( float2 ) test
Building convert_ulong3_sat_rtz( float3 ) test
Building convert_ulong4_sat_rtz( float4 ) test
Building convert_ulong8_sat_rtz( float8 ) test
Building convert_ulong16_sat_rtz( float16 ) test
Testing... .
Error for vector size 2 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 3 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000

Error for vector size 4 found at 0x0001ffd0:  *0x00000000ffffffff vs 0x0000000000000000
Input value: inf  (convert_ulong2_sat_rtz( float2 ))
         *** 769) convert_ulongn_sat_rtz( floatn ) FAILED ** 

```

**Comment by rjodinchr** [comment]
I am not able to repro the async_strided issue with llvmpipe nor Intel. I'll try it on AMD today.

I am able to repro the conversion issue with llvmpipe. I'll work on it.

**Comment by rjodinchr** [comment]
I have a fix for the conversion issue.
It will come as an update of https://reviews.llvm.org/D153456, so wait to review it. I'll upload it tomorrow.

**Comment by rjodinchr** [comment]
https://reviews.llvm.org/D153456 is ready for review

**Comment by rjodinchr** [comment]
I am not able to reproduce the issue with the async tests on AMD. I would tend toward a driver issue on your end.

**Comment by kpet** [comment]
Thanks! Let's see if it disappears after updates at my end.

**Pull request merged**
