### PR TITLE
name build thread

### PR DESCRIPTION
**Pull request by rjodinchr**

### CODE REVIEW

**Comment by rjodinchr** [comment]
I don't understand the issue. Can you rerun the tests please?

**Comment by rjodinchr** [comment]
I think github is having some issues.

**Comment by kpet** [comment]
I've retriggered the failing job a few times and it's always failing. I can't make sense of it but this may be a genuine issue on macOS. If that's the case, I don't understand why we didn't see it on the PR that named executor threads. Maybe you could try disabling thread naming on macOS in the utility function?

**Comment by rjodinchr** [comment]
Thread naming is already disabled on macOS

**Comment by rjodinchr** [comment]
The other PR is having issues with macOS. I think this is an issue with github and macOS.

**Pull request merged**
