### PR TITLE
Add missing headers to event.hpp

### PR DESCRIPTION
**Pull request by amaiorano**
Also add an event.cpp to include event.hpp to ensure the file can be
included without needing to include dependent headers first.

### CODE REVIEW

**Review by kpet — APPROVED** [review]
LGTM, thanks! What environment was this failing in?

**Comment by amaiorano** [comment]
> LGTM, thanks! What environment was this failing in?

Ah, sorry for the lack of detail. This is failing internal builds at Google, specifically when building the clvk nvidia CTS, for example.

**Comment by amaiorano** [comment]
Hi again, is it okay to merge this?

**Comment by kpet** [comment]
Thanks! Feel free to suggest additional Github Actions combinations that would have caught the issue. Yes, all fine to merge. Sorry for the slowness but I'm on holiday and not spending much time close to a computer.

**Comment by amaiorano** [comment]
> Yes, all fine to merge. Sorry for the slowness but I'm on holiday and not spending much time close to a computer.

Oh, no worries! Sorry for bothering you while you're on holiday! Thanks again for the review, much appreciated :)

**Pull request merged**
