### PR TITLE
Document BOINC supports clvk

### PR DESCRIPTION
**Pull request by truboxl**
Refer BOINC/boinc#4847

### CODE REVIEW

**Comment by kpet** [comment]
Thanks for testing and creating a PR. clvk was at fault here and I've fixed it with https://github.com/kpet/clvk/pull/386. Was that the only issue you faced? Should this PR be changed to say "supported" or are there other issues?

**Comment by truboxl** [comment]
Thanks @kpet. I will verify with the latest clvk commit once I got back.
There's still other issues like how BOINC does not like max freq as 0MHz for FLOPS calculation and they just assign 100Giga FLOPS...

**Comment by kpet** [comment]
Great, thanks! Feel free to open a PR to change the default frequency to some plausible (500 MHz?) hard-coded value. I can see applications tripping over that 0 if they attempt to use it in calculations (they shouldn't!!).

**Review by kpet — APPROVED** [review]
Thanks!

**Pull request merged**
