### PR TITLE
Implement clGetKernelInfo with CL_KERNEL_ATTRIBUTES

### PR DESCRIPTION
**Pull request by FMarno**
This depends on this change to CLSPV - https://github.com/google/clspv/pull/990, which itself depends on changes to SPIRV-Headers - https://github.com/KhronosGroup/SPIRV-Headers/pull/308.

This contribution is being made by Codeplay on behalf of Samsung.

### CODE REVIEW

**Comment by FMarno** [comment]
This isn't in a completed state, but I'm going on holiday for two weeks. One of my colleagues may finish the work while I'm away.

**Comment by FMarno** [comment]
Unfortunately I no longer have time to complete this work but it would be a shame if this work was lost since these addition will help toward 100% CTS conformance, specifically the api/kernel_attributes test. If someone would like to pick up this work and finish it then please do. First https://github.com/google/clspv/pull/990 will need to be completed but then I think all that will need to be done is to account for the attribute being optional.

**Comment by rjodinchr** [comment]
I am taking over this PR

**Comment by rjodinchr** [comment]
This PR can be closed in favor of #562

**Comment by kpet** [comment]
@rjodinchr Ok, closing. @FMarno Thanks for setting this into motion!

**Pull request closed without merging**
