### PR TITLE
remove extra parentheses

### PR DESCRIPTION
**Pull request by rjodinchr**
This is breaking in Google infra

### CODE REVIEW

**Review by kpet — APPROVED** [review]
What flagged the issue? Maybe we could add this to the CI on Github?

**Comment by rjodinchr** [comment]
`-Wparentheses-equality` is not supported by the CI compilers. Not sure what to do to help avoid it in the future here.

**Comment by kpet** [comment]
Seems it's only supported by Clang and enabled by `-Wall` that we've already got enabled. Maybe we could add clang build? It's probably time to update the version of Ubuntu too. Anyway, this PR can go in as is.

**Comment by kpet** [comment]
Also: the above reasoning assumes we'd enable `-Werror`, I'll look into that.

**Pull request merged**
